# Generated by Django 6.0.1 on 2026-01-17 04:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cnpj', models.CharField(max_length=18, unique=True)),
                ('cidade', models.CharField(max_length=100)),
                ('endereço', models.TextField(max_length=200)),
                ('bandeira', models.CharField(max_length=100)),
                ('quadro_ideal', models.IntegerField(default=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='is_manager',
        ),
        migrations.AddField(
            model_name='funcionario',
            name='cpf',
            field=models.CharField(max_length=14, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='data_admissao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='data_demissao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='matricula',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='salario_base',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='telefone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='cargo',
            field=models.CharField(choices=[('CEO', 'CEO'), ('GER_SETOR', 'Gerente de Setor (Matriz)'), ('GER_POSTO', 'Gerente de Posto'), ('SUB_GER', 'Subgerente'), ('ESPEC', 'Especialista/Técnico'), ('ASSIST', 'Assistente/Auxiliar'), ('FRENT', 'Frentista')], default='FRENT', max_length=10),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='setor',
            field=models.CharField(choices=[('DIR', 'Diretoria/CEO'), ('COM', 'Comercial'), ('TI', 'Tecnologia da Informação'), ('RH', 'Recursos Humanos'), ('MKT', 'Marketing'), ('ADM', 'Administrativo'), ('OPE', 'Operacional de Pista')], default='OPE', max_length=3),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='posto_trabalho',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipe', to='core.posto'),
        ),
    ]
