# Generated by Django 6.0.1 on 2026-01-20 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_funcionario_matricula'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posto',
            name='endereço',
        ),
        migrations.AddField(
            model_name='posto',
            name='endereco',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='posto',
            name='bandeira',
            field=models.CharField(default='Rede Bellas', max_length=50),
        ),
        migrations.AlterField(
            model_name='posto',
            name='quadro_ideal',
            field=models.IntegerField(default=10, help_text='Quantidade ideal de funcionários'),
        ),
    ]
