# Generated by Django 6.0.1 on 2026-01-20 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_posto_endereço_posto_endereco_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bandeira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='posto',
            name='bandeira',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='postos', to='core.bandeira'),
        ),
    ]
