# Generated by Django 6.0.1 on 2026-01-21 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_bandeira_alter_posto_bandeira'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='setor',
            field=models.CharField(choices=[('DIRETOR', 'Diretoria/CEO'), ('COMERCIAL', 'Comercial'), ('TI', 'Tecnologia da Informação'), ('RH', 'Recursos Humanos'), ('MARKETING', 'Marketing'), ('ADM', 'Administrativo'), ('OPERACIONAL', 'Operacional de Pista')], default='OPERACIONAL', max_length=11),
        ),
    ]
