# Generated by Django 6.0.1 on 2026-01-20 03:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_alter_funcionario_matricula'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaAtivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Ativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('patrimonio', models.CharField(max_length=50, unique=True)),
                ('serial_number', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('USO', 'Em Uso'), ('ESTOQUE', 'Em Estoque (Reserva)'), ('MANUT', 'Em Manutenção'), ('BAIXA', 'Baixado/Descartado')], default='USO', max_length=10)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('anydesk_id', models.CharField(blank=True, max_length=50, null=True)),
                ('data_compra', models.DateField(blank=True, null=True)),
                ('garantia_ate', models.DateField(blank=True, null=True)),
                ('posto_atual', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ativos_ti', to='core.posto')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ti.categoriaativo')),
            ],
        ),
        migrations.CreateModel(
            name='Chamado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('prioridade', models.CharField(choices=[('1', 'Baixa - Dúvida/Solicitação'), ('2', 'Média - Falha Parcial'), ('3', 'Alta - Posto Parado/Vendas Impactadas')], default='2', max_length=1)),
                ('status', models.CharField(choices=[('NOVO', 'Novo'), ('ANDAMENTO', 'Em Atendimento'), ('AGUARDANDO', 'Aguardando Usuário/Terceiro'), ('RESOLVIDO', 'Resolvido'), ('FECHADO', 'Fechado')], default='NOVO', max_length=10)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('fechado_em', models.DateTimeField(blank=True, null=True)),
                ('ativo_relacionado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ti.ativo')),
                ('posto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.posto')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chamados_abertos', to=settings.AUTH_USER_MODEL)),
                ('tecnico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chamados_tecnicos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Acompanhamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('anexo', models.FileField(blank=True, null=True, upload_to='chamados_anexos/')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('is_interno', models.BooleanField(default=False)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('chamado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acompanhamentos', to='ti.chamado')),
            ],
        ),
    ]
