# Generated by Django 6.0.1 on 2026-01-20 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ti', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamado',
            name='arquivo',
            field=models.FileField(blank=True, null=True, upload_to='chamados_anexos/'),
        ),
    ]
